
spring :
  application :
    name : events-service
  datasource:
    name: events-service
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_CONTAINER_PORT:3306}/events-service
    username: root
    password: ${MYSQL_ROOT_PASSWORD:Rohan@2803}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      bootstrap-servers: ${KAFKA_HOST:localhost}:${KAFKA_PORT:9092}



server :
  port : ${SERVER_PORT:8082} 

management:
  endpoints:
    web:
      exposure:
        include: health,info



eureka:
  client:
    service-url:
      defaultZone: http://${DISCOVERY_HOST:localhost}:${DISCOVERY_PORT:8761}/eureka # add this chnage everywhere 


DATA:
  JWT_SECRET : ${JWT_SECRET:abcbsjkshdahdhsahdsahdihaidhiosahdoiashdoi2222}


springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
  redis:
    host: ${REDIS_HOST:redis}
    port: ${REDIS_PORT:6379}





