CREATE DATABASE IF NOT EXISTS booking_service;
CREATE DATABASE IF NOT EXISTS events_service;
CREATE DATABASE IF NOT EXISTS payments_and_notification_service;
CREATE DATABASE IF NOT EXISTS shows_service;
CREATE DATABASE IF NOT EXISTS users_service;