spring :
  application : 
    name : "booking-service"
  datasource:
    name: shows-service
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_CONTAINER_PORT:3306}/booking-service
    username: root
    password: ${MYSQL_ROOT_PASSWORD:Rohan@2803}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  kafka:
    bootstrap-servers: ${KAFKA_HOST:localhost}:${KAFKA_PORT:9092}
    admin:
      auto-create: true
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: rohan-group-01
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: "*"

server :
  port : ${SERVER_PORT:8081}

eureka:
  client:
    service-url:
      defaultZone: http://${DISCOVERY_HOST:localhost}:${DISCOVERY_PORT:8761}/eureka

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

DATA:
  JWT_SECRET : ${JWT_SECRET:abcbsjkshdahdhsahdsahdihaidhiosahdoiashdoi2222}

logging:
  level:
    org:
      springframework:
        security: DEBUG

feign:
  client:
    config:
      default:
        loggerLevel : full
