spring:
  application:
    name: shows-service
  datasource:
    name: shows-service
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_CONTAINER_PORT:3306}/shows-service
    username: root
    password: ${MYSQL_ROOT_PASSWORD:Rohan@2803}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true


server :
  port : ${SERVER_PORT:8083}


eureka:
  client:
    service-url:
      defaultZone: http://${DISCOVERY_HOST:localhost}:${DISCOVERY_PORT:8761}/eureka

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
  redis:
    host: ${REDIS_HOST:redis}
    port: ${REDIS_PORT:6379}


DATA:
  JWT_SECRET : ${JWT_SECRET:abcbsjkshdahdhsahdsahdihaidhiosahdoiashdoi2222}
