spring: 
  application: 
    name: "payments-and-notification-service"
  datasource:
    name: paymentsandnotifictionservice
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_CONTAINER_PORT:3306}/payments-and-notification-service
    username: root
    password: ${MYSQL_ROOT_PASSWORD:Rohan@2803}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  kafka:
    admin:
      auto-create: true
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      bootstrap-servers: ${KAFKA_HOST:localhost}:${KAFKA_PORT:9092}
      properties:
        metadata.max.age.ms: 10
    consumer:
      bootstrap-servers: ${KAFKA_HOST:localhost}:${KAFKA_PORT:9092}
      group-id: rohan-group-01
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
  mail:
    host: smtp.gmail.com
    port: ${SMTP_PORT:587}
    username: ${NEXTSHOW_MAIL:rohankhedekar2803@gmail.com}
    password: jpws grxu xfjw leab
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


stripe:
  secret-key: ${STRIPE_SECRET_KEY:sk_test_51RA7mT4Z4twcya3mhmTNZOtUBzGXFVWOuqrmyMbhU5pw7OFN12yx9MkhGiuQrla2SvkDlTmgbS7E2L14J9BffrPY00UKgpfwJV}
  public-key: ${STRIPE_PUBLIC_KEY:pk_test_51RA7mT4Z4twcya3mrTvKjcMRKF96pR94fxDXoaKCjy5M9cEGWA4eY0cIVBPniPZXaz8UeWQVXG0V85MAnQiE1m0900rFMaoYLa}

app:
  frontend:
    protocol: ${FRONTEND_PROTOCOL:http}
    host: ${FRONTEND_HOST:localhost}
    port: ${FRONTEND_PORT:5173}
    base-url: ${app.frontend.protocol}://${app.frontend.host}:${app.frontend.port}
                                  

server :
  port : ${SERVER_PORT:8084}

eureka:
  client:
    service-url:
      defaultZone: http://${DISCOVERY_HOST:localhost}:${DISCOVERY_PORT:8761}/eureka

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

DATA:
  JWT_SECRET : ${JWT_SECRET:abcbsjkshdahdhsahdsahdihaidhiosahdoiashdoi2222}


management:
  endpoints:
    web:
      exposure:
        include: health,info
